### PR TITLE
fix scratchattch not working.

### PR DESCRIPTION
**Pull request by zayoon013**
I had to remove the shortened name and you need to write the full name of the module.

### CODE REVIEW

**Comment by EngineerRunner** [comment]
that pr changes nothing, it works without this change. that's what "importing as" does, it changes the link to the module from "scratchattach" to "scr"

**Comment by mybearworld** [comment]
Is there any reason to shorten the module name? Just makes the code slightly less readable

**Comment by GenericProgrammer1234** [comment]
@mybearworld Python programmers love aliases that are not needed, if people alias numpy to np then a name as long as scratchattach should be aliased.

**Comment by mybearworld** [comment]
> @mybearworld Python programmers love aliases that are not needed, if people alias numpy to np then a name as long as scratchattach should be aliased.

I don't really understand why anyone would alias `numpy` to `np`... the only reason I can come up with is bad formatters.

**Comment by GenericProgrammer1234** [comment]
> > @mybearworld Python programmers love aliases that are not needed, if people alias numpy to np then a name as long as scratchattach should be aliased.

> I don't really understand why anyone would alias `numpy` to `np`... the only reason I can come up with is bad formatters.

@mybearworld Well people started doing it and now it is just tradition.

**Comment by mybearworld** [comment]
(you don't need to ping me everytime)

**Comment by GenericProgrammer1234** [comment]
I know.

**Pull request closed without merging**
